import {
  Utensils,
  Coffee,
  Car,
  ShoppingBag,
  Home,
  Receipt,
  Gamepad2,
  GraduationCap,
  HeartPulse,
  Laptop,
  Package,
  Briefcase,
  TrendingUp,
  Gift,
  Tag,
  Banknote,
} from "lucide-react"

export interface CategoryDef {
  id: string
  name: string
  icon: string
  component: React.ComponentType<{ className?: string; style?: React.CSSProperties }>
  color: string
  badgeBg: string
  badgeText: string
  softBg: string
}

export const EXPENSE_CATEGORIES = [
  {
    id: "food",
    name: "Food",
    icon: "🍜",
    component: Utensils,
    color: "#f97316", // orange
    badgeBg: "bg-orange-50",
    badgeText: "text-orange-700",
    softBg: "bg-orange-50 text-orange-600",
  },
  {
    id: "drinks",
    name: "Drinks",
    icon: "☕",
    component: Coffee,
    color: "#10b981", // emerald
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-700",
    softBg: "bg-emerald-50 text-emerald-600",
  },
  {
    id: "transportation",
    name: "Transportation",
    icon: "🚕",
    component: Car,
    color: "#3b82f6", // blue
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-700",
    softBg: "bg-blue-50 text-blue-600",
  },
  {
    id: "shopping",
    name: "Shopping",
    icon: "🛍️",
    component: ShoppingBag,
    color: "#ec4899",
    badgeBg: "bg-pink-50",
    badgeText: "text-pink-700",
    softBg: "bg-pink-50 text-pink-600",
  },
  {
    id: "rent",
    name: "Housing",
    icon: "🏠",
    component: Home,
    color: "#8b5cf6",
    badgeBg: "bg-purple-50",
    badgeText: "text-purple-700",
    softBg: "bg-purple-50 text-purple-600",
  },
  {
    id: "bills",
    name: "Bills & Services",
    icon: "💡",
    component: Receipt,
    color: "#f59e0b",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-700",
    softBg: "bg-amber-50 text-amber-600",
  },
  {
    id: "entertainment",
    name: "Entertainment",
    icon: "🎮",
    component: Gamepad2,
    color: "#6366f1",
    badgeBg: "bg-indigo-50",
    badgeText: "text-indigo-700",
    softBg: "bg-indigo-50 text-indigo-600",
  },
  {
    id: "education",
    name: "Education",
    icon: "📚",
    component: GraduationCap,
    color: "#06b6d4",
    badgeBg: "bg-cyan-50",
    badgeText: "text-cyan-700",
    softBg: "bg-cyan-50 text-cyan-600",
  },
  {
    id: "health",
    name: "Health",
    icon: "💊",
    component: HeartPulse,
    color: "#ef4444",
    badgeBg: "bg-red-50",
    badgeText: "text-red-700",
    softBg: "bg-red-50 text-red-600",
  },
  {
    id: "technology",
    name: "Technology",
    icon: "💻",
    component: Laptop,
    color: "#64748b",
    badgeBg: "bg-slate-100",
    badgeText: "text-slate-700",
    softBg: "bg-slate-50 text-slate-600",
  },
  {
    id: "other",
    name: "Other",
    icon: "📦",
    component: Package,
    color: "#9ca3af",
    badgeBg: "bg-zinc-100",
    badgeText: "text-zinc-700",
    softBg: "bg-zinc-100 text-zinc-600",
  },
] as const

export const INCOME_CATEGORIES = [
  {
    id: "salary",
    name: "Salary",
    icon: "💼",
    component: Briefcase,
    color: "#10b981",
    badgeBg: "bg-emerald-50",
    badgeText: "text-emerald-700",
    softBg: "bg-emerald-50 text-emerald-600",
  },
  {
    id: "freelance",
    name: "Freelance",
    icon: "💻",
    component: Laptop,
    color: "#3b82f6",
    badgeBg: "bg-blue-50",
    badgeText: "text-blue-700",
    softBg: "bg-blue-50 text-blue-600",
  },
  {
    id: "investments",
    name: "Investments",
    icon: "📈",
    component: TrendingUp,
    color: "#8b5cf6",
    badgeBg: "bg-purple-50",
    badgeText: "text-purple-700",
    softBg: "bg-purple-50 text-purple-600",
  },
  {
    id: "gift",
    name: "Gift",
    icon: "🎁",
    component: Gift,
    color: "#ec4899",
    badgeBg: "bg-pink-50",
    badgeText: "text-pink-700",
    softBg: "bg-pink-50 text-pink-600",
  },
  {
    id: "sales",
    name: "Sales",
    icon: "🏷️",
    component: Tag,
    color: "#f59e0b",
    badgeBg: "bg-amber-50",
    badgeText: "text-amber-700",
    softBg: "bg-amber-50 text-amber-600",
  },
  {
    id: "other_income",
    name: "Other Income",
    icon: "💵",
    component: Banknote,
    color: "#14b8a6",
    badgeBg: "bg-teal-50",
    badgeText: "text-teal-700",
    softBg: "bg-teal-50 text-teal-600",
  },
] as const
